{
 "title": "Ops Dashboard",
 "time": { "from": "now-11w", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Instances Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(report_date,$__interval),\n  avg(metric_value) AS \"Instances\"\nFROM metrics\nWHERE\n  $__timeFilter(report_date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ram Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(report_date,$__interval),\n  avg(ram_value) AS \"ram_value\"\nFROM ram\nWHERE\n  $__timeFilter(report_date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Improvement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Sales Improvement",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Sales" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  report_date AS \"time\",\n  okr_value AS \"Sales\"\nFROM okr\nWHERE\n  $__timeFilter(report_date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "Users" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  report_date AS \"time\",\n  users_value AS \"Users\"\nFROM users\nWHERE\n  $__timeFilter(report_date)\nORDER BY 1"
    }
   ]
  },
  { "title": "Development", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Code Commits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Commit Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(report_date,$__interval),\n  avg(commit_value) AS \"Commits\"\nFROM code_commits\nWHERE\n  $__timeFilter(report_date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Number of Deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Deployment Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(report_date,$__interval),\n  avg(deployment_value) AS \"Deployments\"\nFROM deployments\nWHERE\n  $__timeFilter(report_date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Feature Branch Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Days" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(report_date,$__interval),\n  avg(deployment_value) AS \"Days\"\nFROM failed_deployments\nWHERE\n  $__timeFilter(report_date)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}