version: "3"
services:

  create-cluster:
    image: google/cloud-sdk
    command: sh ./deploy/gcp/create.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace

  destroy-cluster:
    image: google/cloud-sdk
    command: sh ./deploy/gcp/destroy.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace

  k8s:
    image: femtopixel/kompose
    working_dir: /workspace/deploy/k8s
    entrypoint: ["sh", "build.sh"]
    volumes:
      - ../:/workspace

  gcp:
    image: google/cloud-sdk
    command: sh ./deploy/gcp/deploy.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace
    depends_on:
      - k8s

  gcp-pv:
    image: google/cloud-sdk
    command: sh ./deploy/snapshots/update-pvc-k8s.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace
    depends_on:
      - k8s

  #use-case:
  # docker-compose run k8s
  # then manually edit generated files, then,
  # docker-compose run gcp-nokompose
  gcp-nokompose:
    image: google/cloud-sdk
    command: sh ./deploy/gcp/deploy.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace

  snapshots-deploy:
    image: google/cloud-sdk
    command: sh ./deploy/snapshots/create-pv.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace
    depends_on:
      - k8s

  create-snapshots:
    image: google/cloud-sdk
    command: sh ./deploy/snapshots/create-snapshots.sh
    working_dir: /workspace
    env_file: ./gcp/.env
    volumes:
      - ../:/workspace
