function Wss(){var S='bootstrap',T='begin',U='gwt.codesvr.Wss=',V='gwt.codesvr=',W='Wss',X='startup',Y='DUMMY',Z=0,$=1,_='iframe',ab='position:absolute; width:0; height:0; border:none; left: -1000px;',bb=' top: -1000px;',cb='CSS1Compat',db='<!doctype html>',eb='',fb='<html><head><\/head><body><\/body><\/html>',gb='undefined',hb='readystatechange',ib=10,jb='Chrome',kb='eval("',lb='");',mb='script',nb='javascript',ob='moduleStartup',pb='moduleRequested',qb='Failed to load ',rb='head',sb='meta',tb='name',ub='Wss::',vb='::',wb='gwt:property',xb='content',yb='=',zb='gwt:onPropertyErrorFn',Ab='Bad handler "',Bb='" for "gwt:onPropertyErrorFn"',Cb='gwt:onLoadErrorFn',Db='" for "gwt:onLoadErrorFn"',Eb='#',Fb='?',Gb='/',Hb='img',Ib='clear.cache.gif',Jb='baseUrl',Kb='Wss.nocache.js',Lb='base',Mb='//',Nb='locale',Ob='en',Pb='locale=',Qb=7,Rb='&',Sb='GWT_LOCALE=',Tb=';',Ub=11,Vb='__gwt_Locale',Wb='_',Xb='Unexpected exception in locale detection, using default: ',Yb=2,Zb='user.agent',$b='webkit',_b='safari',ac='msie',bc='ie10',cc=9,dc='ie9',ec=8,fc='ie8',gc='gecko',hc='gecko1_8',ic=3,jc=4,kc='selectingPermutation',lc='Wss.devmode.js',mc='ja',nc='09D0585AD3DD1B66F00CBD13750524AB',oc='25E1F983DEF1F7550AEB34E9DBFB988A',pc='2E8A5BCB334F821FF42EAF4BD0C4AD7F',qc='default',rc='463E14026234D6B4797A3BF9545206F2',sc='58666771238DC6C55020D148390E77CB',tc='6C5783B80DB32D784ECDAEB9983E296A',uc='8ED4940CA09FEB512DAE00A9464FD527',vc='AE04BA062C56F6CBB0CC586AD54C7AAE',wc='B7B45431DEDC2C3E14A5BD45E061AD4E',xc='C493E5CD7E6E147952709FB6C7DD6B56',yc='CD95852DD151EF738FE6C479C56BD034',zc='D782FFE7A9A67CFD07EE633195469B8D',Ac='E27E3E388C8C8F922549C1086CBC9BE5',Bc='EB331934B07EADF375713077497E89A6',Cc='FD678F5B80B13CE31AEB30CB22E48501',Dc=':',Ec='.cache.js',Fc='link',Gc='rel',Hc='stylesheet',Ic='href',Jc='loadExternalRefs',Kc='gwt/standard/standard.css',Lc='WSS.css',Mc='end',Nc='http:',Oc='file:',Pc='_gwt_dummy_',Qc='__gwtDevModeHook:Wss',Rc='Ignoring non-whitelisted Dev Mode URL: ',Sc=':moduleBase';var s=window;var t=document;v(S,T);function u(){var a=s.location.search;return a.indexOf(U)!=-1||a.indexOf(V)!=-1}
function v(a,b){if(s.__gwtStatsEvent){s.__gwtStatsEvent({moduleName:W,sessionId:s.__gwtStatsSessionId,subSystem:X,evtGroup:a,millis:(new Date).getTime(),type:b})}}
Wss.__sendStats=v;Wss.__moduleName=W;Wss.__errFn=null;Wss.__moduleBase=Y;Wss.__softPermutationId=Z;Wss.__computePropValue=null;Wss.__getPropMap=null;Wss.__installRunAsyncCode=function(){};Wss.__gwtStartLoadingFragment=function(){return null};Wss.__gwt_isKnownPropertyValue=function(){return false};Wss.__gwt_getMetaProperty=function(){return null};var w=null;var A=s.__gwt_activeModules=s.__gwt_activeModules||{};A[W]={moduleName:W};Wss.__moduleStartupDone=function(e){var f=A[W].bindings;A[W].bindings=function(){var a=f?f():{};var b=e[Wss.__softPermutationId];for(var c=Z;c<b.length;c++){var d=b[c];a[d[Z]]=d[$]}return a}};var B;function C(){D();return B}
function D(){if(B){return}var a=t.createElement(_);a.id=W;a.style.cssText=ab+bb;a.tabIndex=-1;t.body.appendChild(a);B=a.contentWindow.document;B.open();var b=document.compatMode==cb?db:eb;B.write(b+fb);B.close()}
function F(k){function l(a){function b(){if(typeof t.readyState==gb){return typeof t.body!=gb&&t.body!=null}return /loaded|complete/.test(t.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(t.removeEventListener){t.removeEventListener(hb,d,false)}if(e){clearInterval(e)}}}
if(t.addEventListener){t.addEventListener(hb,d,false)}var e=setInterval(function(){d()},ib)}
function m(c){function d(a,b){a.removeChild(b)}
var e=C();var f=e.body;var g;if(navigator.userAgent.indexOf(jb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(kb));for(var i=Z;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring($,j.length-$)))}h.appendChild(e.createTextNode(lb));g=e.createElement(mb);g.language=nb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=Z;i<c.length;i++){g=e.createElement(mb);g.language=nb;g.text=c[i];f.appendChild(g);d(f,g)}}}
Wss.onScriptDownloaded=function(a){l(function(){m(a)})};v(ob,pb);var n=t.createElement(mb);n.src=k;if(Wss.__errFn){n.onerror=function(){Wss.__errFn(W,new Error(qb+code))}}t.getElementsByTagName(rb)[Z].appendChild(n)}
Wss.__startLoadingFragment=function(a){return I(a)};Wss.__installRunAsyncCode=function(a){var b=C();var c=b.body;var d=b.createElement(mb);d.language=nb;d.text=a;c.appendChild(d);c.removeChild(d)};function G(){var c={};var d;var e;var f=t.getElementsByTagName(sb);for(var g=Z,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,eb);if(j.indexOf(vb)>=Z){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=Z){j=k.substring(Z,m);l=k.substring(m+$)}else{j=k;l=eb}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};w=d;Wss.__errFn=e}
function H(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=Z?a.substring(Z,d+$):eb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=t.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Jb);if(a!=null){return a}return eb}
function h(){var a=t.getElementsByTagName(mb);for(var b=Z;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return eb}
function i(){var a=t.getElementsByTagName(Lb);if(a.length>Z){return a[a.length-$].href}return eb}
function j(){var a=t.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==eb){k=h()}if(k==eb){k=i()}if(k==eb&&j()){k=e(t.location.href)}k=f(k);return k}
function I(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return Wss.__moduleBase+a}
function J(){var k=[];var l=Z;function m(a,b){var c=k;for(var d=Z,e=a.length-$;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var n=[];var o=[];function p(a){var b=o[a](),c=n[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(w){w(a,d,b)}throw null}
o[Nb]=function(){var b=null;var c=Ob;try{if(!b){var d=location.search;var e=d.indexOf(Pb);if(e>=Z){var f=d.substring(e+Qb);var g=d.indexOf(Rb,e);if(g<Z){g=d.length}b=d.substring(e+Qb,g)}}if(!b){var h=t.cookie;var i=h.indexOf(Sb);if(i>=Z){var g=h.indexOf(Tb,i);if(g<Z){g=h.length}b=h.substring(i+Ub,g)}}if(!b){b=__gwt_getMetaProperty(Nb)}if(!b){b=s[Vb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Nb,b)){var j=b.lastIndexOf(Wb);if(j<Z){b=null;break}b=b.substring(Z,j)}}catch(a){alert(Xb+a)}s[Vb]=c;return b||Ob};n[Nb]={'default':Z,'en':$,'ja':Yb};o[Zb]=function(){var a=navigator.userAgent.toLowerCase();var b=t.documentMode;if(function(){return a.indexOf($b)!=-1}())return _b;if(function(){return a.indexOf(ac)!=-1&&(b>=ib&&b<Ub)}())return bc;if(function(){return a.indexOf(ac)!=-1&&(b>=cc&&b<Ub)}())return dc;if(function(){return a.indexOf(ac)!=-1&&(b>=ec&&b<Ub)}())return fc;if(function(){return a.indexOf(gc)!=-1||b>=Ub}())return hc;return eb};n[Zb]={'gecko1_8':Z,'ie10':$,'ie8':Yb,'ie9':ic,'safari':jc};__gwt_isKnownPropertyValue=function(a,b){return b in n[a]};Wss.__getPropMap=function(){var a={};for(var b in n){if(n.hasOwnProperty(b)){a[b]=p(b)}}return a};Wss.__computePropValue=p;s.__gwt_activeModules[W].bindings=Wss.__getPropMap;v(S,kc);if(u()){return I(lc)}var q;try{m([mc,_b],nc);m([mc,bc],oc);m([mc,fc],pc);m([qc,fc],rc);m([mc,dc],sc);m([qc,hc],tc);m([mc,hc],uc);m([Ob,dc],vc);m([Ob,fc],wc);m([qc,bc],xc);m([Ob,bc],yc);m([qc,dc],zc);m([qc,_b],Ac);m([Ob,_b],Bc);m([Ob,hc],Cc);q=k[p(Nb)][p(Zb)];var r=q.indexOf(Dc);if(r!=-1){l=parseInt(q.substring(r+$),ib);q=q.substring(Z,r)}}catch(a){}Wss.__softPermutationId=l;return I(q+Ec)}
function K(){if(!s.__gwt_stylesLoaded){s.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=t.createElement(Fc);b.setAttribute(Gc,Hc);b.setAttribute(Ic,I(a));t.getElementsByTagName(rb)[Z].appendChild(b);__gwt_stylesLoaded[a]=true}}
v(Jc,T);c(Kc);c(Lc);v(Jc,Mc)}
G();Wss.__moduleBase=H();A[W].moduleBase=Wss.__moduleBase;var L=J();if(s){var M=!!(s.location.protocol==Nc||s.location.protocol==Oc);s.__gwt_activeModules[W].canRedirect=M;function N(){var b=Pc;try{s.sessionStorage.setItem(b,b);s.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(M&&N()){var O=Qc;var P=s.sessionStorage[O];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(P)){if(P&&(window.console&&console.log)){console.log(Rc+P)}P=eb}if(P&&!s[O]){s[O]=true;s[O+Sc]=H();var Q=t.createElement(mb);Q.src=P;var R=t.getElementsByTagName(rb)[Z];R.insertBefore(Q,R.firstElementChild||R.children[Z]);return false}}}K();v(S,Mc);F(L);return true}
Wss.succeeded=Wss();